doctrine:
    orm:
        metadata_cache_driver:
            type: pool
            pool: doctrine.system_cache_pool
        query_cache_driver:
            type: pool
            pool: doctrine.system_cache_pool
        result_cache_driver:
            type: pool
            pool: doctrine.result_cache_pool

#services:
#    doctrine.result_cache_provider:
#        class: Symfony\Component\Cache\DoctrineProvider
#        public: false
#        arguments:
#            - '@doctrine.result_cache_pool'
#    doctrine.system_cache_provider:
#        class: Symfony\Component\Cache\DoctrineProvider
#        public: false
#        arguments:
#            - '@doctrine.system_cache_pool'
            
#    redis_cache_service:
#        class: Symfony\Component\Cache\Adapter\RedisAdapter
#        calls:
#            - method: setRedis
#              arguments:
#                - '@redis'
#                    
#    redis:
#        class: Redis
#        public: false
#        calls:
#            - method: connect
#              arguments:
#                - '%env(resolve:REDIS_HOST)%' # or host/ip with port
#            - method: select
#              arguments:
#                - '%env(resolve:REDIS_IDX)%' # change database by index

framework:
    cache:
        pools:
            doctrine.result_cache_pool:
                adapter: cache.app
            doctrine.system_cache_pool:
                adapter: cache.system
